name: Update gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Create file with current time
        run: |
          echo "Current time: $(date)" > current_time.txt

      - name: Commit and push
        run: |
          git add current_time.txt
          git commit -m "Update current_time.txt"
          git push
